### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Mopolino8** [JacobCrabill/FlurryPP#2]
Dear Mr. Crabill

I intend to install FlurryPP on Ubuntu 14.04, but when I executed "make" command  I faced the following error:

g++ -c   -o obj/global.o src/global.cpp
In file included from /usr/include/c++/4.8/chrono:35:0,
                 from src/../include/global.hpp:19,
                 from src/global.cpp:16:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
src/global.cpp:22:17: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
                 ^
compilation terminated.
make: **\* [obj/global.o] Error 1

I greatly appreciate if you could guide me about this issue.

Kind Regards,
Bijan

**Comment by JacobCrabill** [comment]
There are two separate issues the compiler is complaining about, but I believe they are both caused by the same issue - the makefile I provide does not have a default 'make' command; you must choose from one of the possible options in order to build the code:
- make debug mpi=n
- make release mpi=n
- make openmp mpi=n
- make mpidebug
- make mpi2
- make mpi

Any of the MPI build options will require you to specify the location of mpi.h, if the default location is not correct for your system.  The non-MPI builds should work as-is on any recent Ubuntu derivative; for debugging, you can also un-comment the various "-fsanitaize" and "-lasan" options in the makefile; this enables Address Sanitizer, which does Valgrind-type error-checking without running through Valgrind (but from my experience, cannot be used in conjunction with Valgrind).  Let me know if you encounter any further errors!

-Jacob

**Comment by Mopolino8** [comment]
Dear Mr. Crabill

Thanks for your response, and I am sorry for delay in responding.
I chose "make mpi" and It works.

Kind Regards,
Bijan

**Comment by JacobCrabill** [comment]
Good to hear; I've also updated the README to make the uasge of the provided `makefile` more clear.
